Proyectoweb/Proyectoweb/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('Proyectowebapp.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('menu/', include('menu.urls')),
    path('carro/', include('carro.urls')),
    path('peticion/', include('peticion.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyectoweb/carro/urls.py
from django.urls import path

from . import views

app_name = 'carro'

urlpatterns = [

    path('agregar/<int:combo_id>/', views.agregar_combo, name='agregar'),
    path('eliminar/<int:combo_id>/', views.eliminar_combo, name='eliminar'),
    path('restar/<int:combo_id>/', views.restar_combo, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),

]

Proyectoweb/menu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.menu, name='menu'),
   

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyectoweb/carro/models.py
from django.db import models

# Create your models here.

Proyectoweb/menu/models.py
# menu/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import m2m_changed 

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"

    def __str__(self):
        return self.nombre

class Componente(models.Model):
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='menu', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "componente"
        verbose_name_plural = "componentes"

    def mostrar(self):
        print(f'{self.categoria}: {self.nombre} - Precio: {self.precio}')

class Combo(models.Model):
    nombre = models.CharField(max_length=50)
    componentes = models.ManyToManyField(Componente)
    created = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='menu', null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=True)
    precio = models.FloatField(blank=True, null=True)

    class Meta:
        verbose_name = "combo"
        verbose_name_plural = "combos"

    def mostrar(self):
        print(f'Combo: {self.nombre}')
        for componente in self.componentes.all():
            componente.mostrar()
        print(f'Precio Total del Combo: {self.calcular_precio_total()}')

    def calcular_precio_total(self):
        return sum(componente.precio for componente in self.componentes.all())
    

Proyectoweb/carro/views.py
from django.shortcuts import render
from .carro import Carro
from menu.models import Combo

from django.shortcuts import redirect

# Create your views here.

def agregar_combo(request, combo_id):
    carro = Carro(request)
    combo = Combo.objects.get(id=combo_id)
    carro.agregar(combo=combo)
    return redirect("menu")

def eliminar_combo(request, combo_id):
    carro = Carro(request)
    combo = Combo.objects.get(id=combo_id)
    carro.eliminar(combo=combo)
    return redirect("menu")

def restar_combo(request, combo_id):
    carro = Carro(request)
    combo = Combo.objects.get(id=combo_id)
    carro.restar_producto(combo=combo)
    return redirect("menu")

def limpiar_carro(request):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect("menu")

Proyectoweb/menu/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from menu.models import Combo

# Create your views here.
@transaction.atomic
def menu(request):
    combos = Combo.objects.all()
    return render(request, 'menu/menu.html', {'combos':combos})

Proyectoweb/menu/templates/carro/widget.html
<table class="table table-bordered" style="color:white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">Carrito</th>
        </tr>
        <tr>
            <th>Combo</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.combo_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.combo_id %}" class="btn btn-sm btn-success">-</a><br/>
                        {{ value.precio }}€
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-info">
                        No hay productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: {{ importe_total_carro }}€</td>
        </tr>

        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="{% url 'home' %}" class="btn btn-success">Pedir</a>


            </td>
        </tr>
        {% endif %}
    </tfoot>

</table>